<?php

namespace app\api\modules\v1\models;

use yii\db\Expression;
use app\lib\db\ActiveRecord;

class AffiliateIntegration extends ActiveRecord
{
    const REQUEST_METHOD_PUT = 'PUT';

    const RAKUTEN = 1;
    const COMMISSION_FACTORY = 2;
    const COMMISSION_JUNCTION = 3;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%affiliate}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'],'string' ],
            [[
                'name',
                'tracking_link',
                'tracking_id',
                'configs',
                'created_at',
                'updated_at'
            ], 'safe']
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => t('ID'),
            'name' => t('Name'),
            'tracking_link' => t('Affiliate Offer ID'),
            'tracking_id' => t('Affiliate Also Name'),
            'configs' => t('Configuration'),
            'created_at' => t('Created At'),
            'updated_at' => t('Updated At')
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = new Expression('NOW()');
        }

        if (app()->request->method == self::REQUEST_METHOD_PUT) {
            $this->updated_at = new Expression('NOW()');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}