<?php

namespace app\api\modules\v1\models;

use app\lib\db\ActiveRecord;
use yii\db\Expression;

class Category extends ActiveRecord
{
    const REQUEST_METHOD_PUT = 'PUT';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'],'string' ],
            [[
                'name',
                'sort_order',
                'created_at',
                'updated_at'
            ], 'safe']
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => t('ID'),
            'name' => t('Name'),
            'sort_order' => t('Sort Order'),
            'created_at' => t('Created At'),
            'updated_at' => t('Updated At')
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = new Expression('NOW()');
        }

        if (app()->request->method == self::REQUEST_METHOD_PUT) {
            $this->updated_at = new Expression('NOW()');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}