<?php

namespace app\api\modules\v1\models;


use yii\db\Expression;
use app\lib\db\ActiveRecord;

class Retailer extends ActiveRecord
{
    const RETAILER_TYPE_AFFILIATE = 'affiliate';
    const RETAILER_TYPE_DIRECT    = 'direct';

    const REQUEST_METHOD_PUT = 'PUT';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%retailer}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        //@todo define retailer current and affiliate fields
        return [
            [['name'],'string'],
            [[
                'name',
                'description',
                'created_at',
                'updated_at'
            ], 'safe']
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        //@todo define retailer current and affiliate fields
        return [
            'id' => t('ID'),
            'name' => t('Name'),
            'description' => t('Description'),
            'created_at' => t('Created At'),
            'updated_at' => t('Updated At')
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = new Expression('NOW()');
        }

        if (app()->request->method == self::REQUEST_METHOD_PUT) {
            $this->updated_at = new Expression('NOW()');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}